### ISSUE TITLE
Cannot see option "morphs dropped on me create a variable reference"

### ISSUE THREAD

**Issue by anquegi** [Cuis-Smalltalk-Learning/Learning-Cuis#4]
Thanks for doing cuis-smaltalk,

I'm followin the [Quick-UI-tour.md](https://github.com/Cuis-Smalltalk-Learning/Learning-Cuis/blob/master/Quick-UI-Tour.md), and all things worked well, on my Mac OSX using Version 5.0.201708312323 (5.0.201708312323) and using Cuis5.0-3389.image, 

I could see the "morphs dropped on me create a variable reference" option in the menu after clicking the blue triangle

<img width="1280" alt="captura de pantalla 2018-08-09 a las 14 01 19" src="https://user-images.githubusercontent.com/2518346/43897777-79fa431c-9bdd-11e8-9435-1c9601b03d16.png">

**Comment by stephensmith9** [comment]
Looks like this feature was removed? It's not there in image 3430 for me anyway. And the reference to it has been removed from the Quick-UI-tour. I use this feature in Squeak often, not sure why it was removed from Cuis?

**Comment by KenDickey** [comment]
Tutorial changed due to code change
