### ISSUE TITLE
Directly open the debugger without showing the tree options

### ISSUE THREAD

**Issue by anquegi** [Cuis-Smalltalk-Learning/Learning-Cuis#5]
When I tried the exception in the quick-ui-tour
` 'four'  + 3.` 
in the workspace, I cannot see the tree options windows, directly goes to the debugger.

I'm using the macOS Sierra system and the latest Cuis-Smalltalk

<img width="1280" alt="captura de pantalla 2018-08-09 a las 14 30 08" src="https://user-images.githubusercontent.com/2518346/43898950-bfe9be9a-9be0-11e8-8916-035c4479f5fc.png">

**Comment by KenDickey** [comment]
On Thu, 09 Aug 2018 05:32:05 -0700
Antonio Juan Querol <notifications@github.com> wrote:

> When I tried the exception in the quick-ui-tour
> ` 'four'  + 3.` 
> in the workspace, I cannot see the tree options windows, directly goes to the debugger.

Antonio,

Thanks much for this and the other report.

Cuis is always evolving and I have not gone through the tour in some time.

I will update it soon.


Thanks again!
-KenD

**Comment by KenDickey** [comment]
On Thu, 09 Aug 2018 05:32:05 -0700
Antonio Juan Querol <notifications@github.com> wrote:

> When I tried the exception in the quick-ui-tour
> ` 'four'  + 3.` 
> in the workspace, I cannot see the tree options windows, directly goes to the debugger.

OK.  Finally had time to update the Quick UI Tour:

https://github.com/Cuis-Smalltalk-Learning/Learning-Cuis/blob/master/Quick-UI-Tour.md

I made a few changes.

Anyone, please check this and make any suggestions.

Thanks much! 
-KenD

**Comment by stephensmith9** [comment]
Using image 3430 and it looks pretty good. The only confusing thing I ran into was a mention of using Cmd-click to get the World menu to open. This doesn't work. Not sure if you meant select-click or left-click or button1-click? Simply using button1 on its own works for me.

**Comment by KenDickey** [comment]
Tutorial changed to match code change
